#Draft an inventory API client class in an api_client.py file using the public DummyJSON API:
import requests

class InventoryAPIClient:
    """Handles communications with the DummyJSON Products API."""

    def __init__(self, base_url: str = "https://dummyjson.com/products"):
        # TODO: Initialize base_url and a requests.Session instance
        self.base_url = base_url
        self.session = requests.Session()

        pass

    def fetch_page(self, limit: int = 30, skip: int = 0) -> dict:
        """Fetch a single page of product data using query parameters."""
        request_url = f"{self.base_url}?limit={limit}&skip={skip}"
        response = self.session.get(request_url,verify=False)
        #response = self.session.get(request_url,verify=False)
        return response.json()  # Return the parsed JSON response

        # TODO: Send a GET request with 'limit' and 'skip' params
        # TODO: Handle HTTP errors (status codes)
        # TODO: Return parsed JSON response dictionary
        #pass

    def fetch_all_products(self, batch_size: int = 30) -> list[dict]:
        """Paginate through all endpoints until all inventory items are retrieved."""
        # TODO: Implement pagination loop using skip offset
        # TODO: Aggregate products into a single list and return it
        all_products = []
        skip = 0
        while True:
            page_data = self.fetch_page(limit=batch_size, skip=skip)
            products = page_data.get("products", [])
            if not products:
                break  # Exit loop if no more products are returned
            all_products.extend(products)
            skip += batch_size
        
        return all_products
        #pass

#2) Draft an report generator class that takes the raw data generated by an API client object and works on it:


#3) Draft a main.py file where an object of each class is properly initialized and used to generate the reports. keep